# Python Automation testing and deploy example

# This template allows you to push your robot from your BitBucket repository to your configured
# Control Room. This configuration will run an automation's unit tests via `rcc` as part of
# any pull request and deploy the project upon merge/commit to the Control Room depending
# on the configured deployments.

# Prerequisites:
# You must configure the following variables within your BitBucket repository settings:
# * $CR_ACCESS_CREDENTIALS: This is the access token for your Control Room account and can be set
#   per deployment or globally within your repository.
# * $CR_ENDPOINT_URL: This is the API endpoint per the Control Room API helper for uploading a robot.
# * $ROBOT_ID: This is the ID of the robot within the Control Room Robot UI. You should set this for
#   each deployment you have configured.
# * $WORKSPACE_ID: This is the workspace ID associated with the deployment. You should set this for
#   each deployment you have configured.
# The ROBOT_ID and WORKSPACE_ID should be configured at the deployment level so each pipeline deploys
# to the correct Workspace.
#
# The robot in control room must be configured as a `robot file` type of robot.
# For more information on creating/getting these values in control room, check out https://robocorp.com/docs/rcc/workflow
definitions:
  caches:
    robocorp-cache:
      key:
        files:
          - robot.yaml
          - conda.yaml
      path: ~/.robocorp

  script:
    &installRcc curl -o rcc https://downloads.robocorp.com/rcc/releases/latest/linux64/rcc &&
    chmod a+x rcc &&
    mv rcc /usr/local/bin/

  steps:
    - step: &deploy
        name: Deploy to Control Room
        script:
          - *installRcc
          - >
            rcc cloud push 
            -r $ROBOT_ID 
            -w $WORKSPACE_ID 
            --account $CR_ACCESS_CREDENTIALS:$CR_ENDPOINT_URL

    - step: &test
        name: Run Unit Tests
        script:
          - *installRcc
          - rcc run -t "UNIT TESTS"
        caches:
          - robocorp-cache

image: atlassian/default-image:latest

pipelines:
  branches:
    main:
      - step:
          <<: *deploy
          deployment: Production
    test:
      - step:
          <<: *deploy
          deployment: Staging
    dev:
      - step:
          <<: *deploy
          deployment: Test

  pull-requests:
    main:
      - step: *test
    test:
      - step: *test
    dev:
      - step: *test
