channels:
  - conda-forge

dependencies:
  - python=3.10.12 
  - pytest=8.2.0
  - python-dotenv=1.0.1
  - pip:
      - robocorp==2.0.2 # https://pypi.org/project/robocorp
      - robocorp-browser==2.3.3 # https://pypi.org/project/robocorp-browser
      - robocorp-log-pytest==0.0.4 # https://pypi.org/project/robocorp-log-pytest
      - robocorp-excel==0.4.4 # https://pypi.org/project/robocorp-excel
      - prodict==0.8.18 # https://pypi.org/project/prodict
