# Control Room deploy example

# This pipeline will push the robot code to the various environments in control room.
# It will push to the environment that matches the name of the branch configured in the trigger
# of each job.  For example, if the trigger is set to `dev`, it will push to the `dev` environment.

# Prerequisites:
# You must configure the following variable groups with noted variables:
# * <environment>-workspace-id (where <environment> matches the names of your workspaces)
#   - WORKSPACE_ID
# * control-room-deploy-credentials
#   - CR_ACCESS_CREDENTIALS
#   - CR_ENDPOINT_URL

# The robot in control room must be configured as a `robot file` type of robot.
# For more information on creating/getting these values in control room, check out https://robocorp.com/docs/rcc/workflow

trigger:
  branches:
    include:
      - dev
      - test
      - prod

jobs:
  - template: control-room-deploy.yml
    parameters:
      workspace: Dev
      ROBOT_ID: "<<robot id>>"
  - template: control-room-deploy.yml
    parameters:
      workspace: Test
      ROBOT_ID: "<<robot id>>"
  - template: control-room-deploy.yml
    parameters:
      workspace: Prod
      ROBOT_ID: "<<robot id>>"
