# This template will deploy to Control Room depending on the
# workspace parameter passed in when triggered by Continuous
# Integration.

parameters:
  - name: robot_id
    type: string
  - name: workspace_id
    type: string
  - name: cr_access_credentials
    type: string
  - name: cr_endpoint_url
    type: string

jobs:
  - job: DeployToControlRoom
    displayName: "Deploy to Control Room"
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
      - template: install-rcc.yml
      - script: >
          rcc cloud push --robot ${{ parameters.robot_id }}
          --workspace ${{ parameters.workspace_id }}
          --account ${{ parameters.cr_access_credentials }}:${{ parameters.cr_endpoint_url }}
        displayName: "Push to Control Room"
