# This template will deploy to Control Room depending on the
# workspace parameter passed in when triggered by Continuous
# Integration.

parameters:
  - name: variable_group_name
    type: string
  - name: cr_access_credentials
    type: string
  - name: cr_endpoint_url
    type: string

jobs:
  - job: DeployToControlRoom
    displayName: "Deploy to Control Room"
    condition: >
      and(succeeded(),
      or(eq(variables['Build.Reason'], 'IndividualCI'),
      eq(variables['Build.Reason'], 'Manual'),
      eq(variables['Build.Reason'], 'BatchedCI')))
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: ${{ parameters.variable_group_name }}
    steps:
      - checkout: self
      - template: install-rcc.yml
      - script: >
          rcc cloud push --robot $(ROBOT_ID)
          --workspace $(WORKSPACE_ID)
          --account ${{ parameters.cr_access_credentials }}:${{ parameters.cr_endpoint_url }}
        displayName: "Push to Control Room"
