name: Deploy to Robocorp Control Room

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true

jobs:
  call-robocorp-install-dependencies:
    uses: ./.github/workflows/robocorp-install-dependencies.yml
  deploy:
    needs: call-robocorp-install-dependencies
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy to Robocorp Control Room
        run: |
          rcc cloud push --robot ${{ vars.ROBOT_ID }} \
            --workspace ${{ vars.WORKSPACE_ID }} \
            --account ${{ secrets.CR_ACCESS_CREDENTIALS }}:${{ vars.CR_ENDPOINT_URL }}
