name: Test Robocorp Python Project

on:
  pull_request:
    branches:
      - main
      - test
      - dev
  workflow_call:

jobs:
  call-install-dependencies:
    uses: ./robocorp-install-dependencies.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          rcc run -t "UNIT TESTS"
